repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-aws-credentials
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
