---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo
  namespace: argo
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo
  namespace: argo
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-root-app
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: demo
  destination:
    server: https://kubernetes.default.svc
  sources:
    - path: apps/argo/
      repoURL: 'https://github.com/majandres/vault-secret-mgmt-demo.git'
      targetRevision: main
    - path: apps/demo/
      repoURL: 'https://github.com/majandres/vault-secret-mgmt-demo.git'
      targetRevision: py-demo # TODO change back to main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
