apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo-cd
spec:
  project: vault
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.27.0
      helm:
        server:
          affinity: ""
          ha:
            enabled: true
            raft:
              enabled: true
        releaseName: vault
        valuesObject:
          ui:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
