apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: py-demo
  namespace: argo
spec:
  project: demo
  sources:
    - path: apps/demo/manifests/py-demo
      repoURL: https://github.com/majandres/vault-secret-mgmt-demo.git
      targetRevision: py-demo-argo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo  # TODO change to main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
